spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT} # Environment Variable
  datasource:
    url: ${datasource-url} #Secrets form azure key vault
    username: ${datasource-username} #Secrets form azure key vault
    password: ${datasource-password} #Secrets form azure key vault
  jpa:
    hibernate:
      ddl-auto: none # Turn off the DDL auto generation
